server:
  port: 9201
spring:
  redis:
    host: 192.168.1.3
    port: 6379
  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: http://localhost:8201
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: '#{@ipKeyResolver}'
          predicates:
            - Method=GET
logging:
  level:
    org.springframework.cloud.gateway: debug