server:
  port: 8301
spring:
  application:
    name: ribbon-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka
service-url:
  user-service: http://ribbon-user-web