server:
  port: 8601
spring:
  application:
    name: trubine-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
turbine:
  app-config: hystrix-service #指定需要收集信息的服务名称
  cluster-name-expression: new String('default')  #指定服务所属集群
  combine-host-port: true #以主机名和端口来区分服务