server:
  port: 9305
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9301
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: admin-client.log  #添加开启admin的日志监控